name: News Parser CI
on:
  schedule:
    - cron: '0 */3 * * *'
  
  workflow_dispatch:

jobs:

  parse-and-send:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Download last link artifact
        uses: actions/download-artifact@v4
        with:
          name: last-link-data
        
        continue-on-error: true

      - name: Check out repository code
        uses: actions/checkout@v3


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Python parser script
        env:
  
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python parser.py

      - name: Upload last link artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-link-data
          path: last_link.txt
